/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ViewGui;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Kukuh Rahingga P
 */
public class ViewGui extends javax.swing.JFrame {


    /**
     * Creates new form ViewGui
     */
    public ViewGui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelUtama = new javax.swing.JTabbedPane();
        PanelPelanggan = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PelComboBy = new javax.swing.JComboBox<>();
        PelComboTujuan = new javax.swing.JComboBox<>();
        PelBtnCari = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        PelTextKontak = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        PelTextAlamat = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        PelTextTtl = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        PelComboJenis = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        PelBtnAdd = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        PelTextNama = new javax.swing.JTextField();
        PelTextPekerjaan = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        PelBtnLihat = new javax.swing.JButton();
        PelTextCari = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        PelDetil = new javax.swing.JTextArea();
        jScrollPane17 = new javax.swing.JScrollPane();
        PelList = new javax.swing.JTextArea();
        PelBtnRefresh = new javax.swing.JButton();
        PanelPetugas = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        PetDetil = new javax.swing.JTextArea();
        PetComboBy = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        PetComboTujuan = new javax.swing.JComboBox<>();
        PetBtnCari = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        PetComboJenis = new javax.swing.JComboBox<>();
        PetBtnAdd = new javax.swing.JButton();
        PetTextGaji = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        PetTextNama = new javax.swing.JTextField();
        PetTextJabatan = new javax.swing.JTextField();
        PetTextKontak = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        PetTextAlamat = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        PetTextTtl = new javax.swing.JTextField();
        PetBtnLihat = new javax.swing.JButton();
        PetTextCari = new javax.swing.JTextField();
        jScrollPane16 = new javax.swing.JScrollPane();
        PetList = new javax.swing.JTextArea();
        PetBtnRefresh = new javax.swing.JButton();
        PanelTw = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        TwDetil = new javax.swing.JTextArea();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        TwComboBy = new javax.swing.JComboBox<>();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        TwComboTujuan = new javax.swing.JComboBox<>();
        TwBtnCari = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        TwBtnAdd = new javax.swing.JButton();
        TwTextNama = new javax.swing.JTextField();
        TwTextLokasi = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        TwBtnLihat = new javax.swing.JButton();
        TwTextCari = new javax.swing.JTextField();
        jScrollPane15 = new javax.swing.JScrollPane();
        TwList = new javax.swing.JTextArea();
        TwBtnRefresh = new javax.swing.JButton();
        PanelPw = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        PwDetil = new javax.swing.JTextArea();
        jLabel35 = new javax.swing.JLabel();
        PwComboTujuan = new javax.swing.JComboBox<>();
        PwBtnCari = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        PwComboTujuan2 = new javax.swing.JComboBox<>();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        PwBtnAdd = new javax.swing.JButton();
        PwTextNama = new javax.swing.JTextField();
        PwTextDurasi = new javax.swing.JTextField();
        PwTextDomisili = new javax.swing.JTextField();
        PwTextHarga = new javax.swing.JTextField();
        PwTextMax = new javax.swing.JTextField();
        PwBtnCommit = new javax.swing.JButton();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        PwBtnLihat = new javax.swing.JButton();
        PwTextCari = new javax.swing.JTextField();
        PwTextIdPw = new javax.swing.JTextField();
        PwTextIdTw = new javax.swing.JTextField();
        jScrollPane14 = new javax.swing.JScrollPane();
        PwList = new javax.swing.JTextArea();
        PwBtnRefresh = new javax.swing.JButton();
        PanelPerjalanan = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        PerComboTujuan2 = new javax.swing.JComboBox<>();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        PerBtnAdd2 = new javax.swing.JButton();
        PerTextIdPw = new javax.swing.JTextField();
        jLabel57 = new javax.swing.JLabel();
        PerBtnAdd = new javax.swing.JButton();
        PerComboTujuan = new javax.swing.JComboBox<>();
        PerBtnCari = new javax.swing.JButton();
        jLabel60 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        PerTextTgl = new javax.swing.JTextField();
        jLabel63 = new javax.swing.JLabel();
        PerBtnLihat = new javax.swing.JButton();
        PerTextIdPer = new javax.swing.JTextField();
        PerTextCari = new javax.swing.JTextField();
        PerTextIdPel = new javax.swing.JTextField();
        jScrollPane12 = new javax.swing.JScrollPane();
        PerList = new javax.swing.JTextArea();
        jScrollPane13 = new javax.swing.JScrollPane();
        PerDetil = new javax.swing.JTextArea();
        PerBtnRefresh = new javax.swing.JButton();
        BtnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("KELOLA PELANGGAN");

        PelComboBy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Index" }));

        PelComboTujuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lihat Detail", "Delete" }));

        PelBtnCari.setText("Cari / delete");

        jLabel2.setText("Input ID / Index");

        jLabel3.setText("Cari Pelanggan");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Tambah Pelanggan");

        jLabel9.setText("Nama");

        jLabel4.setText("Pekerjaan");

        jLabel10.setText("Jenis Kelamin");

        jLabel5.setText("No Kontak");

        PelComboJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-laki", "Perempuan" }));

        jLabel6.setText("Alamat");

        PelBtnAdd.setText("ADD");

        jLabel7.setText("Tempat tanggal lahir");

        jLabel11.setText("By");

        jLabel12.setText("Tujuan");

        PelBtnLihat.setText("Lihat Semua Pelanggan");

        PelDetil.setEditable(false);
        PelDetil.setColumns(20);
        PelDetil.setRows(5);
        jScrollPane5.setViewportView(PelDetil);

        PelList.setEditable(false);
        PelList.setColumns(20);
        PelList.setRows(5);
        jScrollPane17.setViewportView(PelList);

        PelBtnRefresh.setText("Refresh");

        javax.swing.GroupLayout PanelPelangganLayout = new javax.swing.GroupLayout(PanelPelanggan);
        PanelPelanggan.setLayout(PanelPelangganLayout);
        PanelPelangganLayout.setHorizontalGroup(
            PanelPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPelangganLayout.createSequentialGroup()
                .addGap(307, 307, 307)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelPelangganLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PelBtnLihat, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelPelangganLayout.createSequentialGroup()
                        .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PelBtnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(PanelPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelPelangganLayout.createSequentialGroup()
                        .addGroup(PanelPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPelangganLayout.createSequentialGroup()
                                .addGap(180, 180, 180)
                                .addComponent(jLabel8)
                                .addGap(155, 155, 155))
                            .addGroup(PanelPelangganLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(PanelPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelPelangganLayout.createSequentialGroup()
                                        .addGroup(PanelPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel6)
                                            .addGroup(PanelPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel5)
                                                .addGroup(PanelPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel4)
                                                    .addComponent(jLabel9)))
                                            .addComponent(jLabel7))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(PanelPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(PanelPelangganLayout.createSequentialGroup()
                                                .addComponent(PelComboJenis, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(PelBtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(PelTextPekerjaan, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(PelTextKontak, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(PelTextAlamat, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(PelTextTtl)
                                            .addComponent(PelTextNama)))
                                    .addGroup(PanelPelangganLayout.createSequentialGroup()
                                        .addGroup(PanelPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel12))
                                        .addGap(26, 26, 26)
                                        .addGroup(PanelPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(PelComboBy, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(PelComboTujuan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(PelBtnCari, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(PelTextCari))))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPelangganLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(153, 153, 153))))
        );
        PanelPelangganLayout.setVerticalGroup(
            PanelPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPelangganLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(PanelPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelPelangganLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(PelTextCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PelComboBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(12, 12, 12)
                        .addGroup(PanelPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PelComboTujuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PelBtnCari)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(PelTextNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(PelTextPekerjaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(PelTextKontak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(PelTextAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(PanelPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(PelTextTtl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(PelComboJenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PelBtnAdd)
                            .addComponent(PelBtnRefresh)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPelangganLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PanelPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane17)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PelBtnLihat)
                        .addGap(29, 29, 29)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        PanelUtama.addTab("Kelola Pelanggan", PanelPelanggan);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setText("KELOLA PETUGAS");

        PetDetil.setEditable(false);
        PetDetil.setColumns(20);
        PetDetil.setRows(5);
        jScrollPane4.setViewportView(PetDetil);

        PetComboBy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Index" }));

        jLabel14.setText("By");

        jLabel15.setText("Tujuan");

        PetComboTujuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lihat Detail", "Delete" }));

        PetBtnCari.setText("Cari / delete");

        jLabel16.setText("Input ID / Index");

        jLabel17.setText("Cari Petugas");

        jLabel18.setText("Jenis Kelamin");

        PetComboJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-laki", "Perempuan" }));

        PetBtnAdd.setText("ADD");

        jLabel20.setText("Gaji");

        jLabel21.setText("Jabatan");

        jLabel22.setText("No Kontak");

        jLabel23.setText("Alamat");

        jLabel24.setText("Tempat tanggal lahir");

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel25.setText("Tambah Petugas");

        jLabel26.setText("Nama");

        PetBtnLihat.setText("Lihat Semua Petugas");

        PetList.setEditable(false);
        PetList.setColumns(20);
        PetList.setRows(5);
        jScrollPane16.setViewportView(PetList);

        PetBtnRefresh.setText("Refresh");

        javax.swing.GroupLayout PanelPetugasLayout = new javax.swing.GroupLayout(PanelPetugas);
        PanelPetugas.setLayout(PanelPetugasLayout);
        PanelPetugasLayout.setHorizontalGroup(
            PanelPetugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPetugasLayout.createSequentialGroup()
                .addGroup(PanelPetugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelPetugasLayout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addComponent(jLabel13))
                    .addGroup(PanelPetugasLayout.createSequentialGroup()
                        .addGroup(PanelPetugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelPetugasLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(PetBtnLihat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(PanelPetugasLayout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 2, Short.MAX_VALUE))
                            .addGroup(PanelPetugasLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(PetBtnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(PanelPetugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelPetugasLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(PanelPetugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelPetugasLayout.createSequentialGroup()
                                        .addGroup(PanelPetugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel16)
                                            .addComponent(jLabel15))
                                        .addGap(21, 21, 21)
                                        .addGroup(PanelPetugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(PetComboBy, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(PetComboTujuan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(PetBtnCari, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(PetTextCari)))
                                    .addGroup(PanelPetugasLayout.createSequentialGroup()
                                        .addGroup(PanelPetugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel20)
                                            .addGroup(PanelPetugasLayout.createSequentialGroup()
                                                .addGroup(PanelPetugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel26)
                                                    .addComponent(jLabel21)
                                                    .addComponent(jLabel22)
                                                    .addComponent(jLabel23)
                                                    .addComponent(jLabel24)
                                                    .addComponent(jLabel18))
                                                .addGap(14, 14, 14)
                                                .addGroup(PanelPetugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addGroup(PanelPetugasLayout.createSequentialGroup()
                                                        .addComponent(PetComboJenis, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGap(101, 101, 101)
                                                        .addComponent(PetBtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(PetTextJabatan, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(PetTextGaji, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(PetTextKontak, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(PetTextAlamat, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(PetTextTtl, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(PetTextNama, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(0, 2, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPetugasLayout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addGap(141, 141, 141))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPetugasLayout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(161, 161, 161)))))
                .addContainerGap())
        );
        PanelPetugasLayout.setVerticalGroup(
            PanelPetugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPetugasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelPetugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelPetugasLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addGroup(PanelPetugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane16)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE))
                        .addGap(13, 13, 13)
                        .addComponent(PetBtnLihat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PetBtnRefresh))
                    .addGroup(PanelPetugasLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelPetugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(PetTextCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelPetugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PetComboBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(12, 12, 12)
                        .addGroup(PanelPetugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PetComboTujuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PetBtnCari)
                        .addGap(73, 73, 73)
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelPetugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(PetTextNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelPetugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(PetTextJabatan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelPetugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(PetTextGaji, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelPetugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PetTextKontak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelPetugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PetTextAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelPetugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PetTextTtl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelPetugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(PetComboJenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PetBtnAdd))
                        .addGap(20, 20, 20)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        PanelUtama.addTab("Kelola Petugas", PanelPetugas);

        jLabel27.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel27.setText("KELOLA TEMPAT WISATA");

        TwDetil.setEditable(false);
        TwDetil.setColumns(20);
        TwDetil.setRows(5);
        jScrollPane6.setViewportView(TwDetil);

        jLabel28.setText("Input ID / Index");

        jLabel29.setText("Cari Tempat Wisata");

        TwComboBy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Index" }));

        jLabel30.setText("By");

        jLabel31.setText("Tujuan");

        TwComboTujuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lihat Detail", "Delete" }));

        TwBtnCari.setText("Cari / delete");

        jLabel32.setText("Lokasi");

        TwBtnAdd.setText("ADD");

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel37.setText("Tambah Tempat Wisata");

        jLabel38.setText("Nama tempat wisata");

        TwBtnLihat.setText("Lihat Semua Tempat Wisata");

        TwList.setEditable(false);
        TwList.setColumns(20);
        TwList.setRows(5);
        jScrollPane15.setViewportView(TwList);

        TwBtnRefresh.setText("Refresh");

        javax.swing.GroupLayout PanelTwLayout = new javax.swing.GroupLayout(PanelTw);
        PanelTw.setLayout(PanelTwLayout);
        PanelTwLayout.setHorizontalGroup(
            PanelTwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTwLayout.createSequentialGroup()
                .addGap(302, 302, 302)
                .addComponent(jLabel27)
                .addGap(11, 11, 11))
            .addGroup(PanelTwLayout.createSequentialGroup()
                .addGroup(PanelTwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PanelTwLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelTwLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TwBtnLihat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PanelTwLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TwBtnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(PanelTwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTwLayout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(jLabel29)
                        .addGap(172, 172, 172))
                    .addGroup(PanelTwLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(PanelTwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelTwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTwLayout.createSequentialGroup()
                                    .addGap(178, 178, 178)
                                    .addComponent(jLabel37)
                                    .addGap(125, 125, 125))
                                .addGroup(PanelTwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TwBtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(PanelTwLayout.createSequentialGroup()
                                        .addGroup(PanelTwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel32)
                                            .addComponent(jLabel38))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TwTextLokasi, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(PanelTwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(TwTextNama, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelTwLayout.createSequentialGroup()
                                    .addGap(17, 17, 17)
                                    .addGroup(PanelTwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel30)
                                        .addComponent(jLabel28)
                                        .addComponent(jLabel31))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(PanelTwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(TwBtnCari, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                                        .addComponent(TwComboTujuan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(TwComboBy, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(TwTextCari, javax.swing.GroupLayout.Alignment.TRAILING))))))))
        );
        PanelTwLayout.setVerticalGroup(
            PanelTwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTwLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelTwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PanelTwLayout.createSequentialGroup()
                        .addGroup(PanelTwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
                            .addComponent(jScrollPane15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addComponent(TwBtnLihat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TwBtnRefresh))
                    .addGroup(PanelTwLayout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelTwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(TwTextCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelTwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TwComboBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel30))
                        .addGap(12, 12, 12)
                        .addGroup(PanelTwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TwComboTujuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel31))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TwBtnCari)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel37)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelTwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel38)
                            .addComponent(TwTextNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelTwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel32)
                            .addComponent(TwTextLokasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(TwBtnAdd)))
                .addGap(18, 18, 18))
        );

        PanelUtama.addTab("Kelola Tempat Wisata", PanelTw);

        jLabel33.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel33.setText("KELOLA PAKET WISATA");

        PwDetil.setEditable(false);
        PwDetil.setColumns(20);
        PwDetil.setRows(5);
        jScrollPane8.setViewportView(PwDetil);

        jLabel35.setText("Tujuan");

        PwComboTujuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lihat Detail", "Delete" }));

        PwBtnCari.setText("Cari / delete");

        jLabel36.setText("Input ID");

        jLabel39.setText("Cari paket Wisata");

        jLabel40.setText("Olah Tujuan Wisata");

        jLabel41.setText("Input ID Paket Wisata");

        PwComboTujuan2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "tambah", "hapus" }));

        jLabel42.setText("Tujuan");

        jLabel43.setText("Input ID Tempat Wisata");

        jLabel34.setText("Tambah Paket Wisata");

        PwBtnAdd.setText("ADD");

        PwBtnCommit.setText("Commit");

        jLabel44.setText("Nama paket");

        jLabel45.setText("Durasi");

        jLabel46.setText("Domisili");

        jLabel47.setText("Harga");

        jLabel48.setText("Max Pelanggan");

        PwBtnLihat.setText("Lihat Semua Paket Wisata");

        PwList.setEditable(false);
        PwList.setColumns(20);
        PwList.setRows(5);
        jScrollPane14.setViewportView(PwList);

        PwBtnRefresh.setText("Refresh");

        javax.swing.GroupLayout PanelPwLayout = new javax.swing.GroupLayout(PanelPw);
        PanelPw.setLayout(PanelPwLayout);
        PanelPwLayout.setHorizontalGroup(
            PanelPwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPwLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelPwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelPwLayout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addComponent(jLabel33)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PanelPwLayout.createSequentialGroup()
                        .addGroup(PanelPwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(PanelPwLayout.createSequentialGroup()
                                .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(PwBtnLihat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PwBtnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(PanelPwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelPwLayout.createSequentialGroup()
                                .addGroup(PanelPwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(PanelPwLayout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addGroup(PanelPwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPwLayout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(jLabel48)
                                                .addGap(18, 18, 18)
                                                .addComponent(PwTextMax, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(PanelPwLayout.createSequentialGroup()
                                                .addComponent(jLabel47)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(PwTextHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(PanelPwLayout.createSequentialGroup()
                                                .addComponent(jLabel46)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(PwTextDomisili, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(PanelPwLayout.createSequentialGroup()
                                                .addComponent(jLabel45)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(PwTextDurasi, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(PanelPwLayout.createSequentialGroup()
                                                .addComponent(jLabel44)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(PwTextNama, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPwLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(PanelPwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(PwBtnAdd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(PwBtnCommit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(PanelPwLayout.createSequentialGroup()
                                                .addGroup(PanelPwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(PanelPwLayout.createSequentialGroup()
                                                        .addGap(125, 125, 125)
                                                        .addComponent(PwBtnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(PanelPwLayout.createSequentialGroup()
                                                        .addGap(54, 54, 54)
                                                        .addGroup(PanelPwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel36)
                                                            .addComponent(jLabel35))
                                                        .addGap(31, 31, 31)
                                                        .addGroup(PanelPwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(PwTextCari, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(PwComboTujuan, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(PanelPwLayout.createSequentialGroup()
                                                .addGroup(PanelPwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel41)
                                                    .addComponent(jLabel43)
                                                    .addComponent(jLabel42))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(PanelPwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(PwComboTujuan2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(PwTextIdTw)
                                                    .addComponent(PwTextIdPw))))))
                                .addContainerGap(41, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPwLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(PanelPwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPwLayout.createSequentialGroup()
                                        .addComponent(jLabel39)
                                        .addGap(155, 155, 155))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPwLayout.createSequentialGroup()
                                        .addComponent(jLabel40)
                                        .addGap(147, 147, 147))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPwLayout.createSequentialGroup()
                                        .addComponent(jLabel34)
                                        .addGap(143, 143, 143))))))))
        );
        PanelPwLayout.setVerticalGroup(
            PanelPwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPwLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelPwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelPwLayout.createSequentialGroup()
                        .addGroup(PanelPwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
                            .addComponent(jScrollPane14))
                        .addGap(18, 18, 18)
                        .addComponent(PwBtnLihat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PwBtnRefresh))
                    .addGroup(PanelPwLayout.createSequentialGroup()
                        .addComponent(jLabel39)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelPwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PwTextCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel36))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelPwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel35)
                            .addComponent(PwComboTujuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PwBtnCari)
                        .addGap(16, 16, 16)
                        .addComponent(jLabel40)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelPwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel41)
                            .addComponent(PwTextIdPw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelPwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel43)
                            .addComponent(PwTextIdTw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(PanelPwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PwComboTujuan2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel42))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PwBtnCommit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel34)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelPwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PwTextNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel44))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelPwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PwTextDurasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel45))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelPwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PwTextDomisili, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel46))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelPwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PwTextHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel47))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelPwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PwTextMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel48))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PwBtnAdd)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        PanelUtama.addTab("Kelola Paket Wisata", PanelPw);

        jLabel49.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel49.setText("KELOLA PERJALANAN");

        jLabel51.setText("Tanggal Perjalanan");

        jLabel52.setText("Olah Peserta Perjalanan");

        jLabel53.setText("Input ID Perjalanan");

        PerComboTujuan2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "tambah", "hapus" }));

        jLabel54.setText("Tujuan");

        jLabel55.setText("Input ID Pelanggan");

        jLabel56.setText("Tambah Perjalanan");

        PerBtnAdd2.setText("ADD");

        jLabel57.setText("Tujuan");

        PerBtnAdd.setText("ADD");

        PerComboTujuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lihat Detail", "Delete" }));

        PerBtnCari.setText("Cari / delete");

        jLabel60.setText("Input ID");

        jLabel62.setText("Cari Perjalanan");

        jLabel63.setText("ID Paket Wisata");

        PerBtnLihat.setText("Lihat Semua Perjalanan");

        PerList.setEditable(false);
        PerList.setColumns(20);
        PerList.setRows(5);
        jScrollPane12.setViewportView(PerList);

        PerDetil.setEditable(false);
        PerDetil.setColumns(20);
        PerDetil.setRows(5);
        jScrollPane13.setViewportView(PerDetil);

        PerBtnRefresh.setText("Refresh");

        javax.swing.GroupLayout PanelPerjalananLayout = new javax.swing.GroupLayout(PanelPerjalanan);
        PanelPerjalanan.setLayout(PanelPerjalananLayout);
        PanelPerjalananLayout.setHorizontalGroup(
            PanelPerjalananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPerjalananLayout.createSequentialGroup()
                .addGap(302, 302, 302)
                .addComponent(jLabel49)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelPerjalananLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelPerjalananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PerBtnLihat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPerjalananLayout.createSequentialGroup()
                        .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PerBtnRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(PanelPerjalananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPerjalananLayout.createSequentialGroup()
                        .addGap(0, 35, Short.MAX_VALUE)
                        .addGroup(PanelPerjalananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPerjalananLayout.createSequentialGroup()
                                .addGroup(PanelPerjalananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(PerBtnAdd2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(PanelPerjalananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPerjalananLayout.createSequentialGroup()
                                            .addComponent(jLabel63)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(PerTextIdPw, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPerjalananLayout.createSequentialGroup()
                                            .addComponent(jLabel51)
                                            .addGap(18, 18, 18)
                                            .addComponent(PerTextTgl, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(PerBtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPerjalananLayout.createSequentialGroup()
                                .addComponent(jLabel56)
                                .addGap(133, 133, 133))))
                    .addGroup(PanelPerjalananLayout.createSequentialGroup()
                        .addGroup(PanelPerjalananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelPerjalananLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(PanelPerjalananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel53)
                                    .addGroup(PanelPerjalananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel54)
                                        .addComponent(jLabel55)))
                                .addGap(18, 18, 18)
                                .addGroup(PanelPerjalananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PerComboTujuan2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(PerTextIdPel)
                                    .addComponent(PerTextIdPer)))
                            .addGroup(PanelPerjalananLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(PanelPerjalananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel62)
                                    .addComponent(jLabel52)))
                            .addGroup(PanelPerjalananLayout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addGroup(PanelPerjalananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel60)
                                    .addComponent(jLabel57))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(PanelPerjalananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PerComboTujuan, 0, 305, Short.MAX_VALUE)
                                    .addComponent(PerTextCari)
                                    .addComponent(PerBtnCari, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(26, 26, 26))))
        );
        PanelPerjalananLayout.setVerticalGroup(
            PanelPerjalananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPerjalananLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel49)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelPerjalananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelPerjalananLayout.createSequentialGroup()
                        .addComponent(jLabel62)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelPerjalananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel60)
                            .addComponent(PerTextCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelPerjalananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel57)
                            .addComponent(PerComboTujuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addComponent(PerBtnCari)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel52)
                        .addGap(14, 14, 14)
                        .addGroup(PanelPerjalananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel53)
                            .addComponent(PerTextIdPer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelPerjalananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel55)
                            .addComponent(PerTextIdPel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(PanelPerjalananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel54)
                            .addComponent(PerComboTujuan2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PerBtnAdd)
                        .addGap(72, 72, 72)
                        .addComponent(jLabel56)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelPerjalananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PerTextTgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel51))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PerTextIdPw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PerBtnAdd2))
                    .addGroup(PanelPerjalananLayout.createSequentialGroup()
                        .addGroup(PanelPerjalananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane12, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
                            .addComponent(jScrollPane13))
                        .addGap(18, 18, 18)
                        .addGroup(PanelPerjalananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel63)
                            .addComponent(PerBtnLihat))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PerBtnRefresh)))
                .addContainerGap())
        );

        PanelUtama.addTab("Kelola Perjalanan", PanelPerjalanan);

        BtnExit.setText("EXIT");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelUtama, javax.swing.GroupLayout.PREFERRED_SIZE, 811, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PanelUtama, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnExit)
                .addGap(5, 5, 5))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnExit;
    private javax.swing.JPanel PanelPelanggan;
    private javax.swing.JPanel PanelPerjalanan;
    private javax.swing.JPanel PanelPetugas;
    private javax.swing.JPanel PanelPw;
    private javax.swing.JPanel PanelTw;
    private javax.swing.JTabbedPane PanelUtama;
    private javax.swing.JButton PelBtnAdd;
    private javax.swing.JButton PelBtnCari;
    private javax.swing.JButton PelBtnLihat;
    private javax.swing.JButton PelBtnRefresh;
    private javax.swing.JComboBox<String> PelComboBy;
    private javax.swing.JComboBox<String> PelComboJenis;
    private javax.swing.JComboBox<String> PelComboTujuan;
    private javax.swing.JTextArea PelDetil;
    private javax.swing.JTextArea PelList;
    private javax.swing.JTextField PelTextAlamat;
    private javax.swing.JTextField PelTextCari;
    private javax.swing.JTextField PelTextKontak;
    private javax.swing.JTextField PelTextNama;
    private javax.swing.JTextField PelTextPekerjaan;
    private javax.swing.JTextField PelTextTtl;
    private javax.swing.JButton PerBtnAdd;
    private javax.swing.JButton PerBtnAdd2;
    private javax.swing.JButton PerBtnCari;
    private javax.swing.JButton PerBtnLihat;
    private javax.swing.JButton PerBtnRefresh;
    private javax.swing.JComboBox<String> PerComboTujuan;
    private javax.swing.JComboBox<String> PerComboTujuan2;
    private javax.swing.JTextArea PerDetil;
    private javax.swing.JTextArea PerList;
    private javax.swing.JTextField PerTextCari;
    private javax.swing.JTextField PerTextIdPel;
    private javax.swing.JTextField PerTextIdPer;
    private javax.swing.JTextField PerTextIdPw;
    private javax.swing.JTextField PerTextTgl;
    private javax.swing.JButton PetBtnAdd;
    private javax.swing.JButton PetBtnCari;
    private javax.swing.JButton PetBtnLihat;
    private javax.swing.JButton PetBtnRefresh;
    private javax.swing.JComboBox<String> PetComboBy;
    private javax.swing.JComboBox<String> PetComboJenis;
    private javax.swing.JComboBox<String> PetComboTujuan;
    private javax.swing.JTextArea PetDetil;
    private javax.swing.JTextArea PetList;
    private javax.swing.JTextField PetTextAlamat;
    private javax.swing.JTextField PetTextCari;
    private javax.swing.JTextField PetTextGaji;
    private javax.swing.JTextField PetTextJabatan;
    private javax.swing.JTextField PetTextKontak;
    private javax.swing.JTextField PetTextNama;
    private javax.swing.JTextField PetTextTtl;
    private javax.swing.JButton PwBtnAdd;
    private javax.swing.JButton PwBtnCari;
    private javax.swing.JButton PwBtnCommit;
    private javax.swing.JButton PwBtnLihat;
    private javax.swing.JButton PwBtnRefresh;
    private javax.swing.JComboBox<String> PwComboTujuan;
    private javax.swing.JComboBox<String> PwComboTujuan2;
    private javax.swing.JTextArea PwDetil;
    private javax.swing.JTextArea PwList;
    private javax.swing.JTextField PwTextCari;
    private javax.swing.JTextField PwTextDomisili;
    private javax.swing.JTextField PwTextDurasi;
    private javax.swing.JTextField PwTextHarga;
    private javax.swing.JTextField PwTextIdPw;
    private javax.swing.JTextField PwTextIdTw;
    private javax.swing.JTextField PwTextMax;
    private javax.swing.JTextField PwTextNama;
    private javax.swing.JButton TwBtnAdd;
    private javax.swing.JButton TwBtnCari;
    private javax.swing.JButton TwBtnLihat;
    private javax.swing.JButton TwBtnRefresh;
    private javax.swing.JComboBox<String> TwComboBy;
    private javax.swing.JComboBox<String> TwComboTujuan;
    private javax.swing.JTextArea TwDetil;
    private javax.swing.JTextArea TwList;
    private javax.swing.JTextField TwTextCari;
    private javax.swing.JTextField TwTextLokasi;
    private javax.swing.JTextField TwTextNama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane8;
    // End of variables declaration//GEN-END:variables
    
    // =============== Code Untuk Kelola Pelanggan ===============
    // Button -----
    public JButton getPelBtnLihat() {
        return PelBtnLihat;
    }
    
    public JButton getPelBtnRefresh() {
        return PelBtnRefresh;
    }

    public JButton getPelBtnCari() {
        return PelBtnCari;
    }
    
    public JButton getPelBtnAdd() {
        return PelBtnAdd;
    }
    
    // Get Text -----
    public String getPelTextCari() {
        return PelTextCari.getText();
    }
    
    public String getPelTextNama() {
        return PelTextNama.getText();
    }
    
    public String getPelTextPekerjaan() {
        return PelTextPekerjaan.getText();
    }
    
    public String getPelTextKontak() {
        return PelTextKontak.getText();
    }
    
    public String getPelTextAlamat() {
        return PelTextAlamat.getText();
    }
    
    public String getPelTextTtl() {
        return PelTextTtl.getText();
    }
    
    // Set Text -----
    public void setPelList(String s) {
        PelList.setText(s);
    }
    
    public void setPelDetil(String s) {
        PelDetil.setText(s);
    }
    
    // Combo Box -----
    public int getPelComboBy() {
        return PelComboBy.getSelectedIndex() + 1;
    }
    
    public int getPelComboTujuan() {
        return PelComboTujuan.getSelectedIndex() + 1;
    }
    
    public int getPelComboJenis() {
        return PelComboJenis.getSelectedIndex() + 1;
    } 
    

    
    // =============== Code Untuk Kelola Petugas =============== 
    // Button -----
    public JButton getPetBtnLihat() {
        return PetBtnLihat;
    }
    
    public JButton getPetBtnRefresh() {
        return PetBtnRefresh;
    }
    
    public JButton getPetBtnCari() {
        return PetBtnCari;
    }
    
    public JButton getPetBtnAdd() {
        return PetBtnAdd;
    }
    
    // Text -----
    public String getPetTextCari() {
        return PetTextCari.getText();
    }
    
    public String getPetTextNama() {
        return PetTextNama.getText();
    }
    
    public String getPetTextJabatan() {
        return PetTextJabatan.getText();
    }
    
    public String getPetTextGaji() {
        return PetTextGaji.getText();
    }
    
    public String getPetTextKontak() {
        return PetTextKontak.getText();
    }
    
    public String getPetTextAlamat() {
        return PetTextAlamat.getText();
    }
    
    public String getPetTextTtl() {
        return PetTextTtl.getText();
    }
    
    // Set Text -----
    public void setPetList(String s) {
        PetList.setText(s);
    }
    
    public void setPetDetil(String s) {
        PetDetil.setText(s);
    }
    
    // Combo Box -----
    public int getPetComboBy() {
        return PetComboBy.getSelectedIndex() + 1;
    }
    
    public int getPetComboTujuan() {
        return PetComboTujuan.getSelectedIndex() + 1;
    }
    
    public int getPetComboJenis() {
        return PetComboJenis.getSelectedIndex() + 1;
    }
       
    
    
    // =============== Code Untuk Kelola Tempat Wisata =============== 
    // Button -----
    public JButton getTwBtnLihat() {
        return TwBtnLihat;
    }
    
    public JButton getTwBtnRefresh() {
        return TwBtnRefresh;
    }
    
    public JButton getTwBtnCari() {
        return TwBtnCari;
    }
    
    public JButton getTwBtnAdd() {
        return TwBtnAdd;
    }
    
    // Text -----
    public String getTwTextCari() {
        return TwTextCari.getText();
    }
    
    public String getTwTextNama() {
        return TwTextNama.getText();
    }
    
    public String getTwTextLokasi() {
        return TwTextLokasi.getText();
    }
    
    // Set Text -----
    public void setTwList(String s) {
        TwList.setText(s);
    }
    
    public void setTwDetil(String s) {
        TwDetil.setText(s);
    }
    
    // Combo Box -----
    public int getTwComboBy() {
        return TwComboBy.getSelectedIndex() + 1;
    }
    
    public int getTwComboTujuan() {
        return TwComboTujuan.getSelectedIndex() + 1;
    }
    
    
    
    // =============== Code Untuk Kelola Paket Wisata =============== 
    // Button -----
    public JButton getPwBtnLihat() {
        return PwBtnLihat;
    }
    
    public JButton getPwBtnRefresh() {
        return PwBtnRefresh;
    }
    
    public JButton getPwBtnCari() {
        return PwBtnCari;
    }
    
    public JButton getPwBtnCommit() {
        return PwBtnCommit;
    }
    
    public JButton getPwBtnAdd() {
        return PwBtnAdd;
    }
    
    // Text -----
    public String getPwTextCari() {
        return PwTextCari.getText();
    }
    
    public String getPwTextIdPw() {
        return PwTextIdPw.getText();
    }
    
    public String getPwTextIdTw() {
        return PwTextIdTw.getText();
    }
    
    public String getPwTextNama() {
        return PwTextNama.getText();
    }
    
    public String getPwTextDurasi() {
        return PwTextDurasi.getText();
    }
    
    public String getPwTextDomisili() {
        return PwTextDomisili.getText();
    }
    
    public String getPwTextHarga() {
        return PwTextHarga.getText();
    }
    
    public String getPwTextMax() {
        return PwTextMax.getText();
    }
    
    // Set Text -----
    public void setPwList(String s) {
        PwList.setText(s);
    }
    
    public void setPwDetil(String s) {
        PwDetil.setText(s);
    }
    
    // Combo Box -----
    public int getPwComboTujuan() {
        return PwComboTujuan.getSelectedIndex() + 1;
    }
    
    public int getPwComboTujuan2() {
        return PwComboTujuan2.getSelectedIndex() + 1;
    }
    
    
    
    // =============== Code Untuk Kelola Perjalanan =============== 
    // Button -----
    public JButton getPerBtnLihat() {
        return PerBtnLihat;
    }
    
    public JButton PergetBtnRefresh() {
        return PerBtnRefresh;
    }
    
    public JButton getPerBtnCari() {
        return PerBtnCari;
    }
    
    public JButton getPerBtnAdd() {
        return PerBtnAdd;
    }
    
    public JButton getPerBtnAdd2() {
        return PerBtnAdd2;
    }
    
    // Text -----
    public String getPerTextCari() {
        return PerTextCari.getText();
    }
    
    public String getPerTextIdPer() {
        return PerTextIdPer.getText();
    }
    
    public String getPerTextIdPel() {
        return PerTextIdPel.getText();
    }
    
    public String getPerTextTgl() {
        return PerTextTgl.getText();
    }
    
    public String getPerTextIdPw() {
        return PerTextIdPw.getText();
    }
    
    // Set Text -----
    public void setPerList(String s) {
        PerList.setText(s);
    }
    
    public void setPerDetil(String s) {
        PerDetil.setText(s);
    }
    
    // Combo Box -----
    public int getPerComboTujuan() {
        return PerComboTujuan.getSelectedIndex() + 1;
    }
    
    public int getPerComboTujuan2() {
        return PerComboTujuan2.getSelectedIndex() + 1;
    }
    
    
    
    // =============== Code Tambahan =============== 
    public JButton getBtnExit() {
        return BtnExit;
    }
    
    public void addActionListener(ActionListener e) {
        BtnExit.addActionListener(e);
        // Pelanggan -----
        PelBtnAdd.addActionListener(e);
        PelBtnCari.addActionListener(e);
        PelBtnLihat.addActionListener(e);
        // Petugas -----
        PetBtnAdd.addActionListener(e);
        PetBtnCari.addActionListener(e);
        PetBtnLihat.addActionListener(e);
        // Tempat Wisata -----
        TwBtnAdd.addActionListener(e);
        TwBtnCari.addActionListener(e);
        TwBtnLihat.addActionListener(e);
        // Paket Wisata -----
        PwBtnAdd.addActionListener(e);
        PwBtnCommit.addActionListener(e);
        PwBtnCari.addActionListener(e);
        PwBtnLihat.addActionListener(e);
        // Perjalanan -----
        PerBtnAdd.addActionListener(e);
        PerBtnAdd2.addActionListener(e);
        PerBtnCari.addActionListener(e);
        PerBtnLihat.addActionListener(e);
    }
    
    public void reset() {
        // Pelanggan -----
        PelTextAlamat.setText("");
        PelTextCari.setText("");
        PelTextKontak.setText("");
        PelTextNama.setText("");
        PelTextPekerjaan.setText("");
        PelTextTtl.setText("");
        PelDetil.setText("");
        PelComboBy.setSelectedIndex(0);
        PelComboJenis.setSelectedIndex(0);
        PelComboTujuan.setSelectedIndex(0);
        // Petugas -----
        PetTextAlamat.setText("");
        PetTextCari.setText("");
        PetTextGaji.setText("");
        PetTextJabatan.setText("");
        PetTextKontak.setText("");
        PetTextNama.setText("");
        PetTextTtl.setText("");
        PetComboBy.setSelectedIndex(0);
        PetComboJenis.setSelectedIndex(0);
        PetComboTujuan.setSelectedIndex(0);
        // Tempat Wisata -----
        TwTextCari.setText("");
        TwTextLokasi.setText("");
        TwTextNama.setText("");
        TwComboBy.setSelectedIndex(0);
        TwComboTujuan.setSelectedIndex(0);
        // Paket Wisata -----
        PwTextCari.setText("");
        PwTextDomisili.setText("");
        PwTextDurasi.setText("");
        PwTextHarga.setText("");
        PwTextIdPw.setText("");
        PwTextIdTw.setText("");
        PwTextMax.setText("");
        PwTextNama.setText("");
        PwComboTujuan.setSelectedIndex(0);
        PwComboTujuan2.setSelectedIndex(0);
        // Perjalanan -----
        PerTextCari.setText("");
        PerTextIdPel.setText("");
        PerTextIdPer.setText("");
        PerTextIdPw.setText("");
        PerTextTgl.setText("");
        PerComboTujuan.setSelectedIndex(0);
        PerComboTujuan2.setSelectedIndex(0);
    }
    
    public void viewErrorMsg(String errorMsg) {
        JOptionPane.showMessageDialog(this, errorMsg);
    }

}
